CREATE table near_earth_object(
  add column neo_reference_id int unique,
  add column name varchar(30),
  add column nasa_jpl_url varchar(50),
  add column absolute_magnitude_h smallint,
  add column estimated_diameter_km_min real,
  add column is_potentially_hazardous_asteroid boolean,
  add column close_approach_dt date,
  add column epoch_date_velocity_approach bigint,
  add column relative_velocity_kmps real,
  add column relative_velocity_kmph real,
  add column relative_velocity_mph real,
  add column miss_distance_astronomical real,
  add column miss_distance_lunar real,
  add column miss_distance_km real,
  add column miss_distance_miles real,
  add column orbiting_body varchar(10),
  add column orbit_id smallint,
  add column orbit_determination_dt varchar(30),
  add column orbit_uncertainity float,
  add column min_orbit_intersection real,
  add column jupiter_tisserand_invariant real,
  add column epoch_osculation real,
  add column eccentricity real,
  add column semi_major_axis real,
  add column inclination real,
  add column ascending_node_longitude real,
  add column orbital_period real,
  add column perihelion_distance real,
  add column perihelion_argument real,
  add column aphelion_distance real,
  add column perihelion_time real,
  add column mean_anomaly real,
  add column mean_motion real,
  add column equinox real
  );
