#Index all neo data in the local db
POST http://localhost:8080/saveAllNeoInDb
Accept: */*
Cache-Control: no-cache
###

POST http://localhost:8080/api/neo/index
Accept: */*
Cache-Control: no-cache
###

GET http://localhost:9090/api/neo/3433759
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
###