CREATE table near_earth_object (
  neo_reference_id int unique,
  name varchar(30),
  nasa_jpl_url varchar(50),
  absolute_magnitude_h smallint,
  estimated_diameter_km_min real,
  is_potentially_hazardous_asteroid boolean,
  close_approach_dt date,
  epoch_date_velocity_approach bigint,
  relative_velocity_kmps real,
  relative_velocity_kmph real,
  relative_velocity_mph real,
  miss_distance_astronomical real,
  miss_distance_lunar real,
  miss_distance_km real,
  miss_distance_miles real,
  orbiting_body varchar(10),
  orbit_id smallint,
  orbit_determination_dt varchar(30),
  orbit_uncertainity float,
  min_orbit_intersection real,
  jupiter_tisserand_invariant real,
  epoch_osculation real,
  eccentricity real,
  semi_major_axis real,
  inclination real,
  ascending_node_longitude real,
  orbital_period real,
  perihelion_distance real,
  perihelion_argument real,
  aphelion_distance real,
  perihelion_time real,
  mean_anomaly real,
  mean_motion real,
  equinox real
);
